// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LinkBlock: typeof import('./src/components/LinkBlock.vue')['default']
    ProjectBlock: typeof import('./src/components/ProjectBlock.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
